import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import Image from "next/image";
import bgImage from "@/public/login-signup-bg.jpg";
import "./globals.css";
import SplitText from "@/components/LogoAnimation";
import { MessageSquareCode } from "lucide-react";
import { Bebas_Neue } from "next/font/google";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const bebas = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {/* Background image */}
      <div className="fixed inset-0 -z-20">
        <Image
          src={bgImage}
          alt="Background"
          fill
          className="object-cover object-center"
          priority
        />
        <div className="absolute inset-0 bg-black/60" />
      </div>
      {/* Content */}
      <div className="relative flex flex-col items-start justify-center h-screen mx-[10.25rem] z-10">
        <div className="flex">
        <MessageSquareCode size={75} className="mt-1 mr-1"/>
        <SplitText
          text="CodeYap"
          className={`text-7xl ${bebas.className}`}
          delay={250}
          animationFrom={{ opacity: 0, transform: "translate3d(0,50px,0)" }}
          animationTo={{ opacity: 1, transform: "translate3d(0,0,0)" }}
          easing="easeOutCubic"
          threshold={0.2}
        />
        </div>
        <div className="w-[25rem] mt-[2rem] text-lg transform transition-transform duration-1000 ease-out translate-y-[-50px] animate-slide-in">
          <p className="opacity-75">
            Welcome to Codeyap – a space where developers connect, share code, discuss ideas, and build together in real time
          </p>
        </div>
      </div>
      <SessionProvider>{children}</SessionProvider>
    </>
  );
}
